## 👋 “Hey” from the Praxis team
## PRAXIS DEFAULT PIPELINES
## tell drone to build and package Praxis output alongside an nginx webserver within a Docker image.
## learn more at praxis.target.com/guides/ci-cd and praxis.target.com/guides/hosting

# SETUP - reuse step configuration (thanks @NicholasCappo)
node-image: &node-image
  image: node:10.15.3

build-commands: &build-commands
  commands:
    - npm install
    - npm run build

deploy-dev: &deploy-dev
  when:
    event: push
    branch: master

docker-settings: &docker-settings
  image: plugins/docker
  registry: docker.target.com
  username: svcpejkn001
  secrets: [docker_password]

## pipelines, run when particular 'event' conditions are satisfied
pipeline:
  #####################
  ## DEV PIPELINE - builds and packages master
  #####################

  ## install, verify and build our source code
  dev-build:
    <<: *deploy-dev
    <<: *node-image
    <<: *build-commands
    environment:
      - REACT_APP_ENV=qa

  ## build a docker image for the dev branch/feature
  dev-build-docker-publish:
    <<: *deploy-dev
    <<: *docker-settings
    repo: docker.target.com/app/reacttestinglibrary
    tags:
      - 'b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}'

secrets:
  docker_password:
    path: /secret/shared/tap/drone-secrets/ARTIFACTORY_SVCPEJKN001_BINREPO
